### ISSUE TITLE
The Future of Athena

### ISSUE THREAD

**Issue by Blacksmoke16** [athena-framework/athena#34]
# Future of Athena

Writing Athena, and its supportive shards, has been a wonderful journey.  I've learned a lot along way as it relates to Crystal, and system design.  This learning process has recently got me thinking about the future of Athena.  No, I'm not abandoning it.  This is more so going to be my manifesto on how I see Athena, its supportive shards, and the Crystal ecosystem working together in the long term.

I wanted to get this out there so for one, I don't forget it, and two, to gather feedback from others in the community.  Even if you don't/never used Athena.  The aim for this document is mainly going to be high level design and organizational in nature.  Hopefully from this, additional issues can be created in the future to start to implement some of the solutions that were decided upon.

## Vision

First, the high level vision of how I see everything working in the future.  Each topic is expanded upon later to add additional detail/examples.  This is by no means final, as the work towards this idea starts; I am sure it will change over time.  Either because of changes in the language or coming up with better ideas over time.

I had a thought that a successful framework should not consist of a opinionated rigid set of tools tied to one singular application, but more of a flexible set of components that can be combined how the user wants in order to get the outcome they want.  That it should be more of the literal definition of "framework" than what most would think of.  Something that `provides a foundation on which software developers can build programs` even if the parts that makeup that foundation are all not part of the same "framework".

It's having high quality, flexible, and robust framework components that would make something not only better to work with, but also allow every project to avoid having to "reinvent the wheel".

* Athena should consist of components that each provided a specific feature. Validation, Serialization, Logging, Dependency Injection, etc
  
  1. Each component should be independent
     - With documentation existing mainly within the code itself via the API docs
  
  3. Each component should be usable outside of the Athena Framework
     - But provide the best experience when all used together
  
  4. Components should be used to "build" an application
     - Provide the high/medium level features and let the user configure things as needed
  
  5. The actual Athena Routing component should be implemented using interfaces vs concrete types
     - Each component defines a way to register itself with the framework
     - Allow for using external component shards, assuming they/the user implements the correct interface

### Components

Currently Athena consists of three major features:

1. Routing
2. CLI commands
3. Dependency Injection

With 2 (3) main supportive shards:

1. [crylog](https://github.com/blacksmoke16/crylog) - Logging
2. [CrSerializer](https://github.com/blacksmoke16/CrSerializer) - Serialization and validations
3. [assert](https://github.com/blacksmoke16/assert) - The new validation shard (yet to be implemented)

#### Organizational Changes

In order to achieve the first bullet point, the main Athena features must be split into their own shards.  All of these components would ideally live in an `athena`, or something similar, Github organization.  The documentation should be moved from the markdown files into the code bases of each shard in order to keep the documentation more in sync with the code.

##### Update Jan 7, 2020
> The API docs can be built to include the required shards as well in order to show the "full picture" for people reading the documentation.
>
> The org is created as [athena-framework](https://github.com/athena-framework)
>
> Shard names will be updated when moving them into the org in order to show they're all from the same namespace, e.x. `athena-event_dispatcher`.  Some shards will be renamed to be more generic, e.x. `assert` => `athena-validator`

#### External Use

All of the components should be able to used independently of each other within projects outside of Athena.  This would allow the Crystal community and even other frameworks/non web based projects to benefit from the components.  Ultimately more people/projects using each component would allow for them to be developed more quickly.  

#### Building Blocks

A component should be defined as a shard providing a focused feature that can be used in conjunction with other components to build an application.  For example if your project needs logging you could use the logging component.  If you need to validate objects, you can use the validation component.  

Each component's API should be defined as if that component would be used on its own, but should be complete enough to allow other components to build integrations based on that API.  I.e. exposing all relevant data, extensible to allow for custom logic, and provide ways to tie into the flow of the process (callbacks/events etc).

#### Interfaces & DI <a href="#interfaces-and-di" id="interfaces-and-di">#</a>

The plan for point #5 is to use DI in order to decouple the concrete types and the interfaces that are to be used.  The routing component would define extensions for each component, in order to register the required public API types as services using the DI component.  These extensions could be required optionally if the application wishes to use that specific component.  I.e. if you don't want logging, you don't have to use the logging component, or if you're using the logging shard outside of Athena, just don't require the extension.  In addition, external shards could also offer their own extensions in order to register their services.  

The routing component would then use the interfaces of these services as dependencies where/when needed.  This allows any shard to be used as long as the interfaces are the same, or the extension provides a way to make them comparable.

In the end this would look something like:

```crystal
# ext/crylog
@[ADI::Register(name: "logger")]
struct Logger
  include LoggerInterface

  ...
end

# some_controller.cr
require "athena/ext/crylog"

class SomeController < ART::Controller
  include ADI::Injectable
  
  # The logger could be injected into anything logging is needed.
  # Each request would have its own logger instance
  def initialize(@logger : LoggerInterface); end
  
  @[ART::Get(path: "some/path")]
  def some_path : String
    @logger.info "Some message"
    ...
  end
end
```

~~The ultimate goal would be all the services to be defined via YAML markup.  This would allow external shards to define their services in a YAML file that would inherently be registered with the DI container when installed/required.  However this would be a long term goal.  Ideally the configuration of the logger would also be handled via YAML markup; which would be used to define the handlers you wish your main logger to use.  Additional named loggers could also be defined if desired.~~

This setup would also work similarly for external shards.  As long as they include the interface and implement the required methods, and are registered with the DI container, they would be injected instead of the standard Athena component.

### Roadmap

A high level overview of things that are required to achieve the outlined goals, fairly ordered by priority.

- [x] Finish the refactor of `CrSerializer`
- [x] Breakout the DI component into its own shards
- [x] Migrate all components into the organization namespace
- [x] Release a new Athena version with the event dispatcher framework, but without validations/logging by default
- [x] Implement the new `serializer` and `validator` components into Athena Routing
- [x] Finalize the DI component to better support point #5
  - [x] Public/private services
  - [x] Optional services
  - [x] Move user defined parameters into the container
  - [ ] Service locators
  - [ ] TBD
- [ ] Refactor Athena to support the interfaces
  - [ ] Possibly a like "core" component to store common types?
  - [ ] ~Support loggers via DI instead of globally available~  This'll be handled by the new `Log` module in the stdlib
  - [x] Remove direct dependency on `CrSerializer` and `assert`
  - [x] Implement extensions for each Athena component
- [x] Re-implement the CLI component

**Comment by Blacksmoke16** [comment]
I think we pretty much accomplished most of what was desired in this ticket. However it's a bit dated at this point, so I'm going to close it as completed.
